version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # This allows only the snapdeck package to be updated
    allow:
      - dependency-name: "snapdeck"
    # This ensures it updates even for Major versions (like 1.x to 2.x)
    versioning-strategy: increase